// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('ui')['NButton']
    NCol: typeof import('ui')['NCol']
    NCollapse: typeof import('ui')['NCollapse']
    NCollapseTransition: typeof import('ui')['NCollapseTransition']
    NContainer: typeof import('ui')['NContainer']
    NHero: typeof import('ui')['NHero']
    NNavHeader: typeof import('ui')['NNavHeader']
    NRow: typeof import('ui')['NRow']
  }
}

export { }
