// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('./components/base/NButton/index.vue')['default']
    NCol: typeof import('./components/base/NCol/index.vue')['default']
    NCollapse: typeof import('./components/compound/NCollapse/index.vue')['default']
    NCollapseTransition: typeof import('./components/base/NCollapseTransition/index.vue')['default']
    NContainer: typeof import('./components/base/NContainer/index.vue')['default']
    NFooter: typeof import('./components/base/NFooter/index.vue')['default']
    NHero: typeof import('./components/base/NHero/index.vue')['default']
    NImg: typeof import('./components/base/NImg/index.vue')['default']
    NInput: typeof import('./components/base/NInput/index.vue')['default']
    NNavHeader: typeof import('./components/base/NNavHeader/index.vue')['default']
    NRow: typeof import('./components/base/NRow/index.vue')['default']
    NSection: typeof import('./components/base/NSection/index.vue')['default']
  }
}

export { }
